import {DefaultTheme} from "vitepress";

export const sidebar = {
  '/dev-tools/': [
    {
      text: '开发工具',
      collapsible: true,
      collapsed: false,
      items: [
        { text: '编辑器', link: '/dev-tools/editor/' },
        { text: '集成开发环境', link: '/dev-tools/ide/' },
        { text: '数据库', link: '/dev-tools/database-tools/' },
        { text: 'SSH工具', link: '/dev-tools/ssh-tools/' },
        { text: '日志查看', link: '/dev-tools/log-tools/' },
        { text: '接口测试', link: '/dev-tools/api-tools/' },
        { text: 'JSON格式化', link: '/dev-tools/json-tools/' },
        { text: '抓包工具', link: '/dev-tools/packet-capture/' },
        { text: '程序员笔记本', link: '/dev-tools/note-tools/' },
        { text: 'AI开发插件', link: '/dev-tools/ai-dev-plugins/' },
        { text: '服务器面板', link: '/dev-tools/server-panel/' },
        { text: '图表工具', link: '/dev-tools/diagram-tools/' },
      ],
    },
    {
      text: '博客文章',
      collapsible: true,
      collapsed: false,
      items: [
        { text: '高效开发工具推荐', link: '/dev-tools/blog/2026/01/18/高效开发工具推荐' },
        { text: '开发工具配置技巧', link: '/dev-tools/blog/2026/01/19/开发工具配置技巧' },
        { text: '开发工具插件推荐', link: '/dev-tools/blog/2026/01/20/开发工具插件推荐' },
        { text: '开发工具使用心得', link: '/dev-tools/blog/2026/01/21/开发工具使用心得' },
        { text: 'Apifox使用指南', link: '/dev-tools/api-tools/2026/01/17/Apifox使用指南' },
        { text: 'Postman高级用法', link: '/dev-tools/api-tools/2026/01/18/Postman高级用法' },
        { text: 'Webpack配置详解', link: '/dev-tools/build-tools/2026/01/17/Webpack配置详解' },
        { text: 'Vite快速入门', link: '/dev-tools/build-tools/2026/01/18/Vite快速入门' },
        { text: 'DBeaver入门指南', link: '/dev-tools/database-tools/2026/01/17/DBeaver入门指南' },
        { text: 'Navicat使用技巧', link: '/dev-tools/database-tools/2026/01/18/Navicat使用技巧' },
        { text: 'VS Code调试配置', link: '/dev-tools/debug-tools/2026/01/17/VS Code调试配置' },
        { text: 'Chrome DevTools调试技巧', link: '/dev-tools/debug-tools/2026/01/18/Chrome DevTools调试技巧' },
        { text: 'GitHub Actions CI CD', link: '/dev-tools/deployment-tools/2026/01/17/GitHub Actions CI CD' },
        { text: 'Docker基础命令', link: '/dev-tools/deployment-tools/2026/01/18/Docker基础命令' },
        { text: 'Vim基础操作', link: '/dev-tools/editor/2026/01/15/Vim基础操作' },
        { text: 'Sublime Text配置指南', link: '/dev-tools/editor/2026/01/16/Sublime Text配置指南' },
        { text: 'VS Code常用插件推荐', link: '/dev-tools/editor/2026/01/18/VS Code常用插件推荐' },
        { text: 'pnpm使用指南', link: '/dev-tools/package-manager/2026/01/16/pnpm使用指南' },
        { text: 'npm和yarn命令对比', link: '/dev-tools/package-manager/2026/01/17/npm和yarn命令对比' },
        { text: 'Chrome Performance分析', link: '/dev-tools/performance-tools/2026/01/17/Chrome Performance分析' },
        { text: 'Lighthouse性能分析', link: '/dev-tools/performance-tools/2026/01/18/Lighthouse性能分析' },
        { text: 'Cypress端到端测试', link: '/dev-tools/testing-tools/2026/01/17/Cypress端到端测试' },
        { text: 'Jest单元测试入门', link: '/dev-tools/testing-tools/2026/01/18/Jest单元测试入门' },
        { text: 'Git提交规范', link: '/dev-tools/version-control/2026/01/15/Git提交规范' },
        { text: 'Git分支管理策略', link: '/dev-tools/version-control/2026/01/16/Git分支管理策略' },
        { text: 'Git常用命令速查', link: '/dev-tools/version-control/2026/01/18/Git常用命令速查' },
      ],
    },
  ],

  '/tutorials/': [
    {
      text: '开发教程',
      collapsible: true,
      collapsed: false,
      items: [
        { text: 'JAVA教程', link: '/tutorials/java/' },
        { text: 'JAVA框架', link: '/tutorials/java-framework/' },
        { text: '开发源', link: '/tutorials/dev-repo/' },
        { text: '代码托管', link: '/tutorials/code-hosting/' },
        { text: '在线工具', link: '/tutorials/online-tools/' },
        { text: 'AI开发技术', link: '/tutorials/ai-tech/' },
        { text: '开发环境管理', link: '/tutorials/dev-env/' },
        { text: '插件', link: '/tutorials/plugins/' },
        { text: '内外穿透', link: '/tutorials/nat-traversal/' }
      ],
    },
    {
      text: '博客文章',
      collapsible: true,
      collapsed: false,
      items: [
        { text: '前端开发入门指南', link: '/tutorials/blog/2026/01/18/前端开发入门指南' },
        { text: '后端开发最佳实践', link: '/tutorials/blog/2026/01/19/后端开发最佳实践' },
        { text: '全栈开发学习路径', link: '/tutorials/blog/2026/01/20/全栈开发学习路径' },
        { text: '代码审查的重要性', link: '/tutorials/blog/2026/01/21/代码审查的重要性' },
        { text: '个人常用Linux命令', link: '/tutorials/devops/2019/12/31/个人常用Linux命令' },
        { text: '排序算法', link: '/tutorials/algorithm/2026/01/17/排序算法' },
        { text: '数据结构基础', link: '/tutorials/algorithm/2026/01/18/数据结构基础' },
        { text: 'Express框架入门', link: '/tutorials/backend/2026/01/16/Express框架入门' },
        { text: 'Node.js异步编程', link: '/tutorials/backend/2026/01/17/Node.js异步编程' },
        { text: 'MongoDB基础操作', link: '/tutorials/database/2026/01/17/MongoDB基础操作' },
        { text: 'MySQL优化技巧', link: '/tutorials/database/2026/01/18/MySQL优化技巧' },
        { text: 'Jenkins持续集成', link: '/tutorials/devops/2026/01/17/Jenkins持续集成' },
        { text: 'Kubernetes基础', link: '/tutorials/devops/2026/01/18/Kubernetes基础' },
        { text: 'TypeScript基础', link: '/tutorials/frontend/2026/01/16/TypeScript基础' },
        { text: 'React Hooks详解', link: '/tutorials/frontend/2026/01/17/React Hooks详解' },
        { text: 'Vue3组合式API入门', link: '/tutorials/frontend/2026/01/18/Vue3组合式API入门' },
        { text: 'Flutter开发指南', link: '/tutorials/mobile/2026/01/17/Flutter开发指南' },
        { text: 'React Native入门', link: '/tutorials/mobile/2026/01/18/React Native入门' },
      ],
    },
  ],

  '/ai/': [
    {
      text: 'AI相关',
      collapsible: true,
      collapsed: false,
      items: [
        { text: 'AI客户端', link: '/ai/clients/' },
        { text: 'LLM开放平台', link: '/ai/llm-platform/' },
        { text: 'RAG知识库', link: '/ai/rag/' },
        { text: 'AI导航', link: '/ai/navigation/' },
        { text: 'UI设计', link: '/ai/ui-design/' },
        { text: 'LLM镜像', link: '/ai/llm-mirror/' },
        { text: '提示词', link: '/ai/prompts/' },
        { text: 'AI搜索', link: '/ai/search/' },
        { text: 'AI模型库', link: '/ai/models/' },
        { text: '通用大模型', link: '/ai/general-models/' },
        { text: 'tokens供应商', link: '/ai/token-providers/' },
        { text: 'AI产品', link: '/ai/products/' },
        { text: 'MCP', link: '/ai/mcp/' },
        { text: 'Agent Skills', link: '/ai/skills' },
        { text: 'Cursor', link: '/ai/cursor/' },
        { text: 'AI编程插件', link: '/ai/coding/' },
        { text: '教程', link: '/ai/learning/' },
      ],
    },
    {
      text: '博客文章',
      collapsible: true,
      collapsed: false,
      items: [
        { text: 'AI在开发中的应用', link: '/ai/blog/2026/01/18/AI在开发中的应用' },
        { text: '大语言模型使用技巧', link: '/ai/blog/2026/01/19/大语言模型使用技巧' },
        { text: 'AI工具对比分析', link: '/ai/blog/2026/01/20/AI工具对比分析' },
        { text: 'AI辅助学习编程', link: '/ai/blog/2026/01/21/AI辅助学习编程' },
        { text: 'AI图像识别应用', link: '/ai/applications/2026/01/17/AI图像识别应用' },
        { text: 'AI代码生成实践', link: '/ai/applications/2026/01/18/AI代码生成实践' },
        { text: 'AI学习路径', link: '/ai/learning/2026/01/18/AI学习路径' },
        { text: 'GPT模型对比', link: '/ai/models/2026/01/16/GPT模型对比' },
        { text: 'SubAgent 与 Skills：AI Agent 的两种扩展方式', link: '/ai/models/2026/01/17/SubAgent与Skills：AI Agent的两种扩展方式' },
        { text: 'Skill与MCP深度对比', link: '/ai/tools/2026/01/17/Skill与MCP深度对比' },
        { text: 'AI编程工具汇总对比', link: '/ai/tools/2026/01/18/AI编程工具汇总对比' },
        { text: '豆包AI无水印下载', link: '/ai/blog/2026/01/22/doubao-downloader介绍' },
        { text: 'MCP协议使用指南', link: '/ai/blog/2026/01/23/MCP协议使用指南' },
      ],
    },
  ],

  '/online-tools/': [
    {
      text: '在线工具',
      collapsible: true,
      collapsed: false,
      items: [
        { text: '各种工具', link: '/online-tools/various/' },
        { text: '翻译', link: '/online-tools/translate/' },
        { text: 'Markdown', link: '/online-tools/markdown/' },
        { text: '热点资讯', link: '/online-tools/news/' },
        { text: '影视', link: '/online-tools/media/' },
        { text: '在线学习', link: '/online-tools/learning/' },
        { text: '博客分享', link: '/online-tools/blogs/' },
      ],
    },
    {
      text: '博客文章',
      collapsible: true,
      collapsed: false,
      items: [
        { text: '在线工具使用指南', link: '/online-tools/blog/2026/01/18/在线工具使用指南' },
        { text: '在线协作工具推荐', link: '/online-tools/blog/2026/01/19/在线协作工具推荐' },
        { text: '在线学习平台对比', link: '/online-tools/blog/2026/01/20/在线学习平台对比' },
        { text: '在线工具安全使用', link: '/online-tools/blog/2026/01/21/在线工具安全使用' },
        { text: '在线JSON格式化工具', link: '/online-tools/code/2026/01/17/在线JSON格式化工具' },
        { text: '在线代码编辑器推荐', link: '/online-tools/code/2026/01/18/在线代码编辑器推荐' },
        { text: 'PDF转换工具', link: '/online-tools/convert/2026/01/17/PDF转换工具' },
        { text: '在线格式转换工具', link: '/online-tools/convert/2026/01/18/在线格式转换工具' },
        { text: '在线配色工具推荐', link: '/online-tools/design/2026/01/16/在线配色工具推荐' },
        { text: '在线设计工具推荐', link: '/online-tools/design/2026/01/17/在线设计工具推荐' },
        { text: '在线待办清单工具', link: '/online-tools/productivity/2026/01/17/在线待办清单工具' },
        { text: '在线笔记工具推荐', link: '/online-tools/productivity/2026/01/18/在线笔记工具推荐' },
      ],
    },
  ],

  '/computer/': [
    {
      text: '折腾电脑',
      collapsible: true,
      collapsed: false,
      items: [
        { text: 'window优化', link: '/computer/system-optimization/' },
        { text: '文件同步', link: '/computer/file-sync/' },
        { text: '桌面和启动', link: '/computer/desktop/' },
        { text: '效率助理', link: '/computer/efficiency/' },
        { text: '高速下载', link: '/computer/download/' },
        { text: '科学上网', link: '/computer/vpn/' },
        { text: 'NAS存储', link: '/computer/nas/' },
        { text: '远程电脑', link: '/computer/remote/' },
        { text: '视频剪辑', link: '/computer/video-edit/' },
      ],
    },
    {
      text: '基础条件',
      collapsible: true,
      collapsed: false,
      items: [
        { text: '魔法上网', link: '/computer/basics/network/' },
        { text: '鼠标键盘', link: '/computer/basics/peripherals/' },
        { text: '灯桌椅', link: '/computer/basics/desk-setup/' },
        { text: '电脑显示器', link: '/computer/basics/monitor/' },
        { text: '软路由', link: '/computer/basics/router/' },
        { text: '充电头', link: '/computer/basics/charger/' },
      ],
    },
    {
      text: '博客文章',
      collapsible: true,
      collapsed: false,
      items: [
        { text: 'Windows系统优化技巧', link: '/computer/blog/2026/01/18/Windows系统优化技巧' },
        { text: '电脑硬件升级指南', link: '/computer/blog/2026/01/19/电脑硬件升级指南' },
        { text: '软件推荐与配置', link: '/computer/blog/2026/01/20/软件推荐与配置' },
        { text: '电脑故障排查方法', link: '/computer/blog/2026/01/21/电脑故障排查方法' },
        { text: '显卡选购指南', link: '/computer/hardware/2026/01/17/显卡选购指南' },
        { text: 'CPU选购指南', link: '/computer/hardware/2026/01/18/CPU选购指南' },
        { text: 'Mac必备软件推荐', link: '/computer/software/2026/01/17/Mac必备软件推荐' },
        { text: 'Windows必备软件推荐', link: '/computer/software/2026/01/18/Windows必备软件推荐' },
        { text: 'Windows清理技巧', link: '/computer/system-optimization/2026/01/16/Windows清理技巧' },
        { text: 'Windows系统优化技巧', link: '/computer/system-optimization/2026/01/17/Windows系统优化技巧' },
        { text: '常见电脑故障解决', link: '/computer/troubleshooting/2026/01/18/常见电脑故障解决' },
      ],
    },
  ],

  '/browser/': [
    {
      text: '浏览器',
      collapsible: true,
      collapsed: false,
      items: [
        { text: '新标签卡插件', link: '/browser/newtab/' },
        { text: '油猴脚本', link: '/browser/userscript/' },
        { text: '浏览器', link: '/browser/recommend/' },
        { text: '开发插件', link: '/browser/dev-extensions/' },
        { text: '自用插件', link: '/browser/extensions/' },
        { text: '指纹浏览器', link: '/browser/fingerprint/' },
      ],
    },
    {
      text: '博客文章',
      collapsible: true,
      collapsed: false,
      items: [
        { text: '浏览器性能优化', link: '/browser/blog/2026/01/18/浏览器性能优化' },
        { text: '浏览器插件开发入门', link: '/browser/blog/2026/01/19/浏览器插件开发入门' },
        { text: '浏览器安全设置', link: '/browser/blog/2026/01/20/浏览器安全设置' },
        { text: '浏览器使用技巧', link: '/browser/blog/2026/01/21/浏览器使用技巧' },
        { text: 'Chrome高级设置', link: '/browser/config/2026/01/18/Chrome高级设置' },
        { text: '广告拦截插件推荐', link: '/browser/extensions/2026/01/17/广告拦截插件推荐' },
        { text: 'Chrome必备插件推荐', link: '/browser/extensions/2026/01/18/Chrome必备插件推荐' },
        { text: '浏览器性能优化', link: '/browser/tips/2026/01/16/浏览器性能优化' },
        { text: 'Chrome快捷键大全', link: '/browser/tips/2026/01/17/Chrome快捷键大全' },
      ],
    },
  ],
};
